### PR TITLE
Renaming

### PR DESCRIPTION
**Pull request by elstgav**
This renames the story titles to better reflect the contents. Look at the file changes to see what’s changed

### CODE REVIEW

**Comment by me2earth** [comment]
Approved generally. I recall that I couldn’t use this naming schema with Storehouse because the longer titles wouldn’t fit. Couldn’t view the changes as my old link is broken and didn’t see a way in the pull request pane (or elsewhere) for previewing the changes and how they impacted the titles. I’m speculating you corrected the problem by modifying the header style. 

Title for days 13-14 should also include Athens.

Mark Elster
(Sent from my iPad)

**Comment by elstgav** [comment]
Go to https://github.com/me2earth/historic-reflections/pull/2 and tap on the “Changes/Files changed” tab. Oh! And you need to sign in. Your login is in 1Password.

**Comment by me2earth** [comment]
Sound files are missing from video. Any ideas how to recover and link them?

**Comment by elstgav** [comment]
@me2earth The audio works on my end—but the videos are muted by default

**Comment by me2earth** [comment]
Hmm. Doesn’t seem to be an interface element for unmuting them. 

Mark Elster

(sent from my iPhone)

**Pull request merged**
